### ISSUE TITLE
Effectively read/get parameter scalar values across ensemble

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/sumo-tableaggregator#1]
Get the parameter values across an ensemble. `parameter.txt`-parameters.

- [ ] Decide on the format of parameters, metadata or separate file?

Requirements:
- Needs adequate performance/speed

Notes:
- Could be linked to the extraction of tabulated data (separate issue)

**Comment by anders-kiaer** [comment]
Getting access to parameters through the same access pattern as for time series I think would benefit quite some use cases on our side.

I.e. having a concatenated table, similar to time series. In this case it would be a simpler table (instead of `REAL` + `DATES` as multi-index, it would in this case only be `REAL` I guess).

**Comment by daniel-sol** [comment]
This should fit nicely with the future plans, but does involve storing parameters as table per realisation in Sumo. Will then be easy to fit with rest of code.

**Comment by perolavsvendsen** [comment]
But if there are use cases where we want to filter on parameters when querying, we might want it in metadata as today. Don't know if it is practically feasible. If stored as separate table, these need to be downloaded and parsed by every client.

**Comment by daniel-sol** [comment]
Solution now in place, code for this is here https://github.com/equinor/sumo-fmu-aggregation-service
